version: 2

registries:
  ghcr:
    type: docker-registry
    url: https://ghcr.io
    username: x-access-token
    password: ${{ secrets.SHARED_PACKAGES_READ_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    registries:
      - ghcr
    directories:
      - "/backend"
      - "/frontend"
      - "/postgis"
    schedule:
      interval: "daily"
