FROM ghcr.io/kartverket/datadeling-ogcapi-frontend:frontend-v0.2.2@sha256:08249cc798ffaa1ef9dd08be3594bb044e22fbd07a5ba1bf914ab8f454dbeb21

COPY config/pygeoapi-config.yml /apiconfig/config.yml

ENV PYGEOAPI_CONFIG_PATH_FRONTEND=/apiconfig/config.yml
