FROM ghcr.io/kartverket/datadeling-ogcapi-frontend:0.1.2@sha256:27e70428f0961a2e6f80d2c14cf732a1b7884d62d890f76cd93332ca6d6e406a

COPY config/pygeoapi-config.yml /apiconfig/config.yml

ENV PYGEOAPI_CONFIG_PATH_FRONTEND=/apiconfig/config.yml
