FROM ghcr.io/kartverket/datadeling-ogcapi-pygeoapi:pygeoapi-v0.3.0@sha256:17dd166f3da5543b739bba7820af592220bc8b557ff2448cefc5884a86a7915e

USER apprunner

COPY config/pygeoapi-config.yml /pygeoapi/pygeoapi-config.yml
