FROM ghcr.io/kartverket/datadeling-ogcapi-pygeoapi:pygeoapi-v0.2.1@sha256:a40733b89538759a5722b87f4a6bbec668e08ad9d62752ad78eba7e4cbe1b325

COPY config/pygeoapi-config.yml /pygeoapi/pygeoapi-config.yml
