FROM ghcr.io/kartverket/datadeling-ogcapi-pygeoapi:pygeoapi-v0.4.0@sha256:bb9cb0b1f706b6387eab4ab2c2e0f835717d89858ececa3c5ae44d801b79fcc3

USER apprunner

COPY config/pygeoapi-config.yml /pygeoapi/pygeoapi-config.yml
