server:
  bind:
    host: 0.0.0.0
    port: 5000
  cors: true
  url: ${PYGEOAPI_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - en-US
  pretty_print: true
  limits:
    default_items: 20
    max_items: 1000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  admin: false
  templates:
    path: /pygeoapi/custom_templates
    static: /pygeoapi/pygeoapi/static

logging:
  level: INFO

metadata:
  identification:
    title:
      en: Sivilforsvaret - distrikter og kontorer
    description:
      en: >
        Datasett med sivilforsvarsdistrikter og distriktskontor for Sivilforsvaret i Norge.
    keywords:
      en:
        - Sivilforsvaret
        - Sivilforsvarsdistrikt
        - Distriktskontor
        - Beredskap
    keywords_type: theme
    terms_of_service: https://www.kartverket.no
    url: https://www.kartverket.no

  license:
    name: Norge digitalt-lisens
    url: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
  provider:
    name: Direktoratet for samfunnssikkerhet og beredskap (DSB)
    url: https://www.dsb.no
  contact:
    name: Direktoratet for samfunnssikkerhet og beredskap (DSB)
    email: postmottak@dsb.no
    url: https://www.dsb.no

resources:
  get-distinct-values:
    type: process
    processor:
      name: distinct_values.DistinctValuesProcessor
  export-collection-gpkg:
    type: process
    processor:
      name: processes.gpkg_collection.ExportCollectionGpkgProcessor
  export-all-gpkg:
    type: process
    processor:
      name: processes.gpkg_all_collections.ExportAllGpkgProcessor
  export-by-area-gpkg:
    type: process
    processor:
      name: processes.gpkg_by_area.ExportByAreaGpkgProcessor
  export-collection-csv:
    type: process
    processor:
      name: processes.csv_collection.ExportCollectionCsvProcessor

  districts:
    type: collection
    title:
      en: Sivilforsvarsdistrikter
    description:
      en: >
        Polygoner som viser inndelingen av sivilforsvarsdistrikter i Norge.
    keywords:
      en:
        - Sivilforsvaret
        - Sivilforsvarsdistrikt
        - Beredskap
    extents:
      spatial:
        bbox: [4.087524, 57.759005, 31.761592, 71.384878]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: ${DB_HOST}
          dbname: ${DB_NAME}
          user: ${DB_USER}
          password: ${DB_PASSWORD}
          search_path: [public]
        id_field: id
        table: districts
        geom_field: geometry
        storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84


  locations:
    type: collection
    title:
      en: Distriktskontor
    description:
      en: >
        Punkter som viser plasseringen av distriktskontor for Sivilforsvaret i Norge.
    keywords:
      en:
        - Sivilforsvaret
        - Distriktskontor
        - Beredskap
    extents:
      spatial:
        bbox: [4.087524, 57.759005, 31.761592, 71.384878]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: ${DB_HOST}
          dbname: ${DB_NAME}
          user: ${DB_USER}
          password: ${DB_PASSWORD}
          search_path: [public]
        id_field: id
        table: locations
        geom_field: geometry
        storage_crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84

