server:
  bind:
    host: 0.0.0.0
    port: 5000
  cors: true
  url: ${PYGEOAPI_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - en-US
  pretty_print: true
  limits:
    default_items: 20
    max_items: 1000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  admin: false
  templates:
    path: /pygeoapi/custom_templates
    static: /pygeoapi/pygeoapi/static

logging:
  level: INFO

metadata:
  identification:
    title:
      en: Sivilforsvaret - distrikter og kontorer
    description:
      en: >
        Datasett med sivilforsvarsdistrikter og distriktskontor for Sivilforsvaret i Norge.
    keywords:
      en:
        - Sivilforsvaret
        - Sivilforsvarsdistrikt
        - Distriktskontor
        - Beredskap
    keywords_type: theme
    terms_of_service: https://www.kartverket.no
    url: https://www.kartverket.no

  license:
    name: Norge digitalt-lisens
    url: https://www.kartverket.no/geodataarbeid/norge-digitalt/partsinformasjon/avtaler-og-vilkar/norge-digitalt-lisens
  provider:
    name: Kartverket
    url: https://www.kartverket.no
  contact:
    name: Kartverket
    email: post@kartverket.no
    url: https://www.kartverket.no

resources:
  districts:
    type: collection
    title:
      en: Sivilforsvarsdistrikter
    description:
      en: >
        Polygoner som viser inndelingen av sivilforsvarsdistrikter i Norge.
    keywords:
      en:
        - Sivilforsvaret
        - Sivilforsvarsdistrikt
        - Beredskap
    extents:
      spatial:
        bbox: [4.087524, 57.759005, 31.761592, 71.384878]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: GeoJSON
        data: /data/districts.json
        id_field: navn

  locations:
    type: collection
    title:
      en: Distriktskontor
    description:
      en: >
        Punkter som viser plasseringen av distriktskontor for Sivilforsvaret i Norge.
    keywords:
      en:
        - Sivilforsvaret
        - Distriktskontor
        - Beredskap
    extents:
      spatial:
        bbox: [4.087524, 57.759005, 31.761592, 71.384878]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: GeoJSON
        data: /data/locations.json
        id_field: navn
