name: OGC API Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "config/**"

env:
  docker_registry: ghcr.io
  image_name: kartverket/ogc-api-starter-backend # Endre til eget image-navn
  argo_version_file: ogcapi-backend-version

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
      id-token: write

    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      image_url: ${{ steps.set_output.outputs.image_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.docker_registry }}/${{ env.image_name}}
          tags: |
            type=sha,format=long

      - name: Login to Github Container Registry
        uses: docker/login-action@v4.6.0
        with:
          registry: ${{ env.docker_registry }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build docker image and push
        id: docker
        uses: docker/build-push-action@v7
        with:
          context: .
          file: backend/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Summarize Image Digest and Set Output
        id: set_output
        run: |
          echo "Full Image URL: ${{ env.docker_registry }}/${{ env.image_name }}:${{ steps.meta.outputs.version }}@${{steps.docker.outputs.digest}}" >> $GITHUB_STEP_SUMMARY
          echo "image_url=${{ env.docker_registry }}/${{ env.image_name }}:${{ steps.meta.outputs.version }}@${{steps.docker.outputs.digest}}" >> $GITHUB_OUTPUT

  run-pharos:
    name: Run Pharos
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
    permissions:
      actions: read
      packages: read
      contents: read
      security-events: write
    steps:
      - name: "Run Pharos"
        uses: kartverket/pharos@v0.6.4
        with:
          image_url: ${{ needs.build.outputs.image_url }}
          trivy_category: 'Backend'

  argo:
    name: Update version in apps-repo
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Fetch token
        uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: kartverket/datadeling-apps # Endre til eget apps-repo
          identity: ogc-api-starter # Endre til egen chainguard-identity (må være opprettet i apps-repo)
      - name: Checkout apps-repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: kartverket/datadeling-apps # Endre til eget apps-repo
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}
      - name: Update version # Endre sti til versjons-fil iht. eget apps-repo og endre til passende brukernavn for commiten
        run: |
          echo "\"${{ needs.build.outputs.image_url }}\"" > "env/atgcp1-dev/datadeling-ogc-api-starter/${{ env.argo_version_file }}"
          git config --global user.email "noreply@kartverket.no"
          git config --global user.name "Dataprodukter CI"
          git commit -am "Update OGC API ${{ env.argo_version_file }}"
          git push
